name: TANGO_BUILD_6_6_FINAL
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Tools
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bc libelf-dev bison flex libssl-dev
      - name: Get Kernel 6.6
        run: git clone --depth=1 https://github.com/torvalds/linux.git -b v6.6 kernel-src
      - name: Build
        run: |
          cd kernel-src
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules_prepare
          cd ..
          make -C kernel-src M=$GITHUB_WORKSPACE ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KCFLAGS="-Wno-error=all -Wno-error=incompatible-pointer-types" modules
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: tango32_6.6_driver
          path: "**/*.ko"
